substitutions:
  _ENV: dev
  _CLOUD_FUNCTION_LOCATION: europe-west1
  _PROJECT_LOCATION: eu
  _API_PREFIX: https://
  _API_DOMAIN: gcr-tipschef-dev-europe-west1-api-5iymse6mzq-ew.a.run.app
  _API_PORT: '0'
  _PROJECT_ID: tipschef-dev
  _CLOUD_RUN_LOCATION: europe-west1

steps:
  - id: 'Build Docker image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - functions
      - deploy
      - gcf-generate-book-$_ENV-$_PROJECT_LOCATION
      - --runtime=nodejs14
      - --region=$_CLOUD_FUNCTION_LOCATION
      - --source=./generate-book
      - --entry-point=consumePubSub
      - --memory=8Gi
      - --timeout=540s
      - --trigger-event=google.pubsub.topic.publish
      - --trigger-resource=topic-queue-$_ENV-gcf-generate-book
      - --set-env-vars=PROJECT_ID=tipschef-$_ENV,PROJECT_ENV=$_ENV,API_PREFIX=$_API_PREFIX,API_DOMAIN=$_API_DOMAIN,API_PORT=$_API_PORT


